// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0bYvo2lqgqOUfHeaWHlJiuhW2LHykkcA',
    appId: '1:511046313477:web:a8ced013d94d73f6cdde6c',
    messagingSenderId: '511046313477',
    projectId: 'kawiarnia-19e48',
    authDomain: 'kawiarnia-19e48.firebaseapp.com',
    storageBucket: 'kawiarnia-19e48.firebasestorage.app',
    measurementId: 'G-VFD8KJP501',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChA-fVtOhqclU1PMvdHhPBQ18KDYzTLlc',
    appId: '1:511046313477:android:72fdc41f993d3639cdde6c',
    messagingSenderId: '511046313477',
    projectId: 'kawiarnia-19e48',
    storageBucket: 'kawiarnia-19e48.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIGPepRD4lV_0eX4tutaI3Ww_WaI-NTw8',
    appId: '1:511046313477:ios:9f218e7282cc926ecdde6c',
    messagingSenderId: '511046313477',
    projectId: 'kawiarnia-19e48',
    storageBucket: 'kawiarnia-19e48.firebasestorage.app',
    iosBundleId: 'com.example.kawiarnia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIGPepRD4lV_0eX4tutaI3Ww_WaI-NTw8',
    appId: '1:511046313477:ios:9f218e7282cc926ecdde6c',
    messagingSenderId: '511046313477',
    projectId: 'kawiarnia-19e48',
    storageBucket: 'kawiarnia-19e48.firebasestorage.app',
    iosBundleId: 'com.example.kawiarnia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0bYvo2lqgqOUfHeaWHlJiuhW2LHykkcA',
    appId: '1:511046313477:web:6f69ee98e3c52800cdde6c',
    messagingSenderId: '511046313477',
    projectId: 'kawiarnia-19e48',
    authDomain: 'kawiarnia-19e48.firebaseapp.com',
    storageBucket: 'kawiarnia-19e48.firebasestorage.app',
    measurementId: 'G-1ZC4Y69KBB',
  );
}
